spring:
  application:
    name: code-generator
  main:
    allow-bean-definition-overriding: true
smsf:
  codegen:
#    moduleName: sample
    mybatis:
      datasource:
        url: jdbc:mysql://10.237.161.213:3306/smsf_apisp?useUnicode=true&characterEncoding=utf-8
        username: user_dev
        password: Zaq_2wsx
    moduleName: task
    basePackage: com.accenture.smsf.apisp
    resources:
      -
        table-name: t_task
        model-name: Task
      -
        table-name: t_task_template
        model-name: TaskTemplate
